#!/bin/bash

set -e


cd "$(dirname "$(readlink -f "$0")")/.."

if [ "$CI" == "true" ] && [ -z "$AWS_ACCESS_KEY_ID" -o -z "$AWS_SECRET_ACCESS_KEY" ]; then
	echo "Error: AWS credentials must be passed with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables in a CI environment."
	exit 1
fi

# Bootstrap only when necessary
if [ -f .bootstrapped -a "$1" != "--force" ]; then
    exit 0
fi

# Remove environments
rm -rf .venvpython .venv

# Setup Sceptre environment
python -m venv  --prompt "${PWD##*/}-venv" .venv
.venv/bin/pip install --upgrade pip setuptools wheel
.venv/bin/pip install --requirement dependencies/requirements.txt

# Setup test environment for Python lambdas
python -m venv --prompt "${PWD##*/}-venvpython" .venvpython
.venvpython/bin/pip install --upgrade pip setuptools wheel
.venvpython/bin/pip install --requirement dependencies/test_requirements.txt

touch .bootstrapped

