#!/bin/bash

ENVIRONMENT=${1:-dev}
OPTIONS=${@:2}

if [ "$1" = "-h" ]; then
    echo "Usage: $0 [SCEPTRE_ENVIRONMENT] [SCEPTRE_OPTIONS]"
    exit 0
fi

set -e


cd "$(dirname "$(readlink -f "$0")")/.."

./script/bootstrap
PY_DIR=".venv/bin"

${PY_DIR}/sceptre $OPTIONS launch-env $ENVIRONMENT
${PY_DIR}/sceptre describe-env $ENVIRONMENT

${PY_DIR}/sceptre describe-env $ENVIRONMENT | awk -F'[:/]' '{print $1 " " $2}' | xargs -n2 ${PY_DIR}/sceptre describe-stack-outputs
