AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ArtifactsBucketName:
    Description: Name of the S3 bucket to store Lambda function artifacts
    AllowedPattern: "[a-z0-9][a-z0-9.-]{2,62}"
    Type: String

Resources:
  ArtifactsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref ArtifactsBucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  Name:
    Value: !Ref ArtifactsBucketName
  Arn:
    Value: !GetAtt ArtifactsBucket.Arn
