swagger: '2.0'

info:
  title: ServerlessDemo
  description: Dummy API that uses Lambdas as backends
  version: '1.0.0'

basePath: /v1
schemes:
  - https
produces:
  - application/json

definitions:
  Greeting:
    type: string

paths:
  /hello:
    get:
      summary: Say hello

      parameters:
      - name: name
        description: Whom to greet
        in: query
        required: false
        type: string

      responses:
        '200':
          description: Greet someone
          schema:
            $ref: '#/definitions/Greeting'

      x-amazon-apigateway-integration:
        type: aws
        responses:
          default:
            statusCode: '200'

        httpMethod: POST
        credentials: !GetAtt APIGWRole.Arn
        passthroughBehavior: never
        requestTemplates:
          application/json: !Ref MappingTemplate

        uri: !Ref HelloLambdaURI

x-amazon-apigateway-request-validators:
  parameters:
    validateRequestParameters: true
    validateRequestBody: false
x-amazon-apigateway-request-validator: parameters

