openapi: 3.0.1

info:
  title: ServerlessDemo
  description: Dummy API that uses Lambdas as backends
  version: 1.0.0

paths:
  /hello:
    get:
      description: Say hello

      parameters:
      - name: name
        description: Whom to greet
        required: false
        in: query
        schema:
          type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeting"

      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: !Ref HelloLambdaURI
        credentials: !GetAtt APIGWRole.Arn
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT

components:
  schemas:
    Greeting:
      type: string

x-amazon-apigateway-request-validators:
  parameters:
    validateRequestParameters: true
    validateRequestBody: false
x-amazon-apigateway-request-validator: parameters
